# Blog's config.
#
# store the configuration of the blog. Has only one unique entry generated by
# the rake task geewee:config.
#
class GeeweeConfig < ActiveRecord::Base
  ACCEPTED_LOCALES = %w[en fr]

  validates_presence_of :bloguri, :blogtitle, :post_count_per_page, :locale
  validates_presence_of :recaptcha_public_key, :recaptcha_private_key, :if => :use_recaptcha?
  validates_numericality_of :post_count_per_page
  validates_inclusion_of :locale, :in => ACCEPTED_LOCALES

  # hook ensuring to have only one entry.
  def before_create
    not GeeweeConfig.already_configured?
  end

  # return the only entry or a stub.
  def self.entry
    first or new :blogtitle    => 'Your Shiny geewee',
                 :blogsubtitle => 'is almost ready!'
  end

  # return true if there is a valid
  # GeeweeConfig entry.
  def self.already_configured?
    not first.nil?
  end
end
